import type { Cheatsheet } from "@/lib/cheatsheet/types";

export const NETWORK_CHEATSHEET: Cheatsheet = {
  slug: "network",
  title: "20 แนวคิด {highlight} ที่ต้องรู้",
  highlight: "Networking",
  description: "สรุปพื้นฐานเครือข่ายในจอเดียว — แต่ละการ์ดมีภาพย่อและคำอธิบายบรรทัดเดียว กดเพื่ออ่านต่อ",
  items: [
    {
      id: "osi",
      title: "OSI Model",
      caption: "7 ชั้น จากแอปลงถึงสายสัญญาณ",
      accent: "orange",
      diagram: { kind: "custom", name: "osi" },
    },
    {
      id: "packets",
      title: "Packets",
      caption: "ข้อมูลถูกหั่นเป็นชิ้นแล้วส่งทีละก้อน",
      accent: "green",
      diagram: { kind: "custom", name: "packets" },
    },
    {
      id: "ip-address",
      title: "IP Address",
      caption: "ทุกอุปกรณ์มีที่อยู่ของตัวเอง",
      accent: "sky",
      conceptSlug: "ip",
      diagram: { kind: "custom", name: "ip-address" },
    },
    {
      id: "router",
      title: "Router",
      caption: "เชื่อมเครือข่ายต่างวงเข้าด้วยกัน",
      accent: "teal",
      conceptSlug: "router",
      diagram: {
        kind: "scene",
        scene: { type: "hop", label: "route" },
        leftLabel: "LAN",
        rightLabel: "Internet",
      },
    },
    {
      id: "dns",
      title: "DNS",
      caption: "แปลงชื่อโดเมนเป็น IP address",
      accent: "sky",
      conceptSlug: "dns",
      diagram: { kind: "pulse", pulseId: "dns" },
    },
    {
      id: "ports",
      title: "Ports",
      caption: "เครื่องเดียว ให้บริการได้หลายอย่าง",
      accent: "orange",
      diagram: { kind: "custom", name: "ports" },
    },
    {
      id: "nat",
      title: "NAT",
      caption: "หลาย IP ภายใน ออกเน็ตด้วย IP สาธารณะเดียว",
      accent: "teal",
      conceptSlug: "nat",
      diagram: { kind: "pulse", pulseId: "nat" },
    },
    {
      id: "subnets",
      title: "Subnets",
      caption: "แบ่งเครือข่ายใหญ่เป็นบล็อกย่อย",
      accent: "green",
      conceptSlug: "subnetting",
      diagram: { kind: "custom", name: "subnets" },
    },
    {
      id: "dhcp",
      title: "DHCP",
      caption: "แจก IP address ให้อัตโนมัติ",
      accent: "green",
      conceptSlug: "dhcp",
      diagram: { kind: "pulse", pulseId: "dhcp" },
    },
    {
      id: "mac",
      title: "MAC Address",
      caption: "ที่อยู่ฮาร์ดแวร์ที่ฝังมากับการ์ดแลน",
      accent: "sky",
      conceptSlug: "nic",
      diagram: { kind: "custom", name: "mac" },
    },
    {
      id: "arp",
      title: "ARP",
      caption: "ถามหา MAC จาก IP ในวง LAN",
      accent: "green",
      conceptSlug: "arp",
      diagram: { kind: "pulse", pulseId: "arp" },
    },
    {
      id: "switch",
      title: "Switch",
      caption: "ต่ออุปกรณ์หลายเครื่องใน LAN เดียวกัน",
      accent: "orange",
      conceptSlug: "switch",
      diagram: { kind: "custom", name: "switch" },
    },
    {
      id: "tcp",
      title: "TCP",
      caption: "ส่งครบ เรียงลำดับ มีการยืนยัน",
      accent: "green",
      conceptSlug: "tcp",
      diagram: { kind: "pulse", pulseId: "tcp" },
    },
    {
      id: "udp",
      title: "UDP",
      caption: "เร็ว ไม่รอ ack ไม่รับประกัน",
      accent: "orange",
      conceptSlug: "udp",
      diagram: { kind: "pulse", pulseId: "udp" },
    },
    {
      id: "http",
      title: "HTTP/HTTPS",
      caption: "ภาษาของเว็บ แบบเปิดเผย หรือเข้ารหัส",
      accent: "blue",
      conceptSlug: "http",
      diagram: { kind: "pulse", pulseId: "http" },
    },
    {
      id: "tls",
      title: "TLS",
      caption: "จับมือแลกกุญแจก่อน แล้วค่อยเข้ารหัส",
      accent: "purple",
      conceptSlug: "tls",
      diagram: { kind: "pulse", pulseId: "tls" },
    },
    {
      id: "firewall",
      title: "Firewalls",
      caption: "อนุญาตบางพอร์ต บล็อกที่เหลือ",
      accent: "rose",
      conceptSlug: "firewall",
      diagram: { kind: "pulse", pulseId: "firewall" },
    },
    {
      id: "vpn",
      title: "VPN",
      caption: "อุโมงค์ส่วนตัวบนเน็ตสาธารณะ",
      accent: "purple",
      conceptSlug: "vpn",
      diagram: { kind: "pulse", pulseId: "vpn" },
    },
    {
      id: "proxy",
      title: "Proxies",
      caption: "ตัวกลางแทน client หรือแทน server",
      accent: "purple",
      conceptSlug: "proxy",
      diagram: { kind: "pulse", pulseId: "proxy" },
    },
    {
      id: "load-balancer",
      title: "Load Balancers",
      caption: "กระจาย request ไปหลาย server",
      accent: "blue",
      conceptSlug: "load-balancer",
      diagram: { kind: "pulse", pulseId: "load-balancer" },
    },
  ],
};
